---
# Import tasks for the specific OS being built
- include_tasks: "{{ ansible_distribution }}.yml"

- name: install rsyslog output modules
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - omhiredis
    - omrelp

# TODO: install logging setup script
