---
# Import tasks for the specific OS being built
- include_tasks: "{{ ansible_distribution }}.yml"

- name: trust pritunl key
  rpm_key:
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7568D9BB55FF9E5287D586017AE645C0CF8E292A
    state: present

- name: install packages
  package:
    name:
      - "pritunl-{{ pritunl_version }}"
      - mongodb-org
    state: present

- name: disable pritunl and mongod on first boot
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - pritunl
    - mongod
