- name: install openjdk-8 & elasticsearch
  package:
    name:
      - java-1.8.0-openjdk-headless
      - "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
      - nri-elasticsearch
    state: present

- name: remove openjdk-7
  package:
    name: java-1.7.0-openjdk
    state: removed

- name: install elasticsearch ec2 discovery and s3 repository plugins
  shell: '/usr/share/elasticsearch/bin/elasticsearch-plugin install -b discovery-ec2 repository-s3'
