---
# dnsmasq is used for providing split dns lookup services to bypass consul for internet dns queries.
# socat is used for forwarding docker0 requests to consul to localhost for security,
# since iptables forwarding to localhost is not well-supported especially in docker containers.

# Import tasks for the specific OS being built
- include_tasks: "{{ ansible_distribution }}.yml"

- name: install packages
  # Install latest packages
  # noqa 403
  package:
    name:
      - dnsmasq
      - socat
    state: latest

- name: enable dnsmasq
  systemd:
    name: "dnsmasq"
    enabled: true

- name: patch dnsmasq.conf to include /etc/dnsmasq.d
  replace:
    dest: /etc/dnsmasq.conf
    regexp: '^#conf-dir=/etc/dnsmasq.d$'
    replace: 'conf-dir=/etc/dnsmasq.d'

- name: configure dnsmasq
  copy:
    src: etc/dnsmasq.d/10-dnsmasq
    dest: /etc/dnsmasq.d/10-dnsmasq

- name: coredns setup file
  copy:
    src: opt/ivy/set-dnsmasq-dhcp.sh
    dest: /opt/ivy/set-dnsmasq-dhcp.sh
    mode: 0755

- name: copy init files
  copy:
    src: etc/systemd/system/
    dest: /etc/systemd/system/
