name: Run pre-commit

on:
  push:
    branches: [ develop, master, main ]
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Install shellcheck from homebrew
        shell: bash
        run: |
          brew install shellcheck
          hash -r
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
